// Technical Questions Database - 500+ questions
// Format: { question, answer, category }
// Answers kept short (1-3 words) for easy drawing/guessing

const technicalQuestions = [
    // ═══ DATA STRUCTURES (40) ═══
    { question: 'The first node of a tree data structure is called', answer: 'root', category: 'Data Structures' },
    { question: 'What data structure follows FIFO order?', answer: 'queue', category: 'Data Structures' },
    { question: 'What connects a node to another node in a tree?', answer: 'edge', category: 'Data Structures' },
    { question: 'Data structure that follows LIFO order', answer: 'stack', category: 'Data Structures' },
    { question: 'A collection of key-value pairs', answer: 'dictionary', category: 'Data Structures' },
    { question: 'A node with no children in a tree', answer: 'leaf', category: 'Data Structures' },
    { question: 'Data structure with nodes connected by pointers', answer: 'linked list', category: 'Data Structures' },
    { question: 'Tree where each node has at most 2 children', answer: 'binary tree', category: 'Data Structures' },
    { question: 'Collection of unique elements with no duplicates', answer: 'set', category: 'Data Structures' },
    { question: 'Data structure used for fast lookup using keys', answer: 'hash table', category: 'Data Structures' },
    { question: 'A tree that keeps itself balanced automatically', answer: 'AVL tree', category: 'Data Structures' },
    { question: 'Data structure for priority-based processing', answer: 'heap', category: 'Data Structures' },
    { question: 'Graph data structure with no cycles', answer: 'tree', category: 'Data Structures' },
    { question: 'Data structure for storing elements in order', answer: 'array', category: 'Data Structures' },
    { question: 'Structure where first element added is first removed', answer: 'queue', category: 'Data Structures' },
    { question: 'Structure with vertices and edges', answer: 'graph', category: 'Data Structures' },
    { question: 'Hash table collision resolution using linked lists', answer: 'chaining', category: 'Data Structures' },
    { question: 'A double-ended queue', answer: 'deque', category: 'Data Structures' },
    { question: 'A self-referencing data structure', answer: 'linked list', category: 'Data Structures' },
    { question: 'Tree used for storing strings efficiently', answer: 'trie', category: 'Data Structures' },
    { question: 'Data structure for undo operations', answer: 'stack', category: 'Data Structures' },
    { question: 'Ordered binary tree for searching', answer: 'BST', category: 'Data Structures' },
    { question: 'Data structure with front and rear pointers', answer: 'queue', category: 'Data Structures' },
    { question: 'Fixed-size sequential collection of same type', answer: 'array', category: 'Data Structures' },
    { question: 'Data structure used in BFS traversal', answer: 'queue', category: 'Data Structures' },
    { question: 'Data structure used in DFS traversal', answer: 'stack', category: 'Data Structures' },
    { question: 'Matrix representation of a graph', answer: 'adjacency matrix', category: 'Data Structures' },
    { question: 'A circular version of a queue', answer: 'circular queue', category: 'Data Structures' },
    { question: 'Structure where each node points to next node', answer: 'singly linked list', category: 'Data Structures' },
    { question: 'Red and black colored balanced tree', answer: 'red black tree', category: 'Data Structures' },

    // ═══ ALGORITHMS (45) ═══
    { question: 'What is the time complexity of binary search?', answer: 'log n', category: 'Algorithms' },
    { question: 'Sorting algorithm that divides array in half repeatedly', answer: 'merge sort', category: 'Algorithms' },
    { question: 'Search algorithm that checks every element one by one', answer: 'linear search', category: 'Algorithms' },
    { question: 'Sorting by comparing adjacent elements and swapping', answer: 'bubble sort', category: 'Algorithms' },
    { question: 'Algorithm that picks a pivot and partitions around it', answer: 'quick sort', category: 'Algorithms' },
    { question: 'Finding the shortest path in a weighted graph', answer: 'Dijkstra', category: 'Algorithms' },
    { question: 'Solving problems by breaking into smaller subproblems', answer: 'dynamic programming', category: 'Algorithms' },
    { question: 'Algorithm that always makes locally optimal choice', answer: 'greedy', category: 'Algorithms' },
    { question: 'Function that calls itself', answer: 'recursion', category: 'Algorithms' },
    { question: 'Sorting by inserting element in correct position', answer: 'insertion sort', category: 'Algorithms' },
    { question: 'Sorting by selecting minimum element each time', answer: 'selection sort', category: 'Algorithms' },
    { question: 'Traversing a graph level by level', answer: 'BFS', category: 'Algorithms' },
    { question: 'Traversing a graph going as deep as possible first', answer: 'DFS', category: 'Algorithms' },
    { question: 'Algorithm to find minimum spanning tree', answer: 'Kruskal', category: 'Algorithms' },
    { question: 'Divide and conquer sorting with O(n log n)', answer: 'merge sort', category: 'Algorithms' },
    { question: 'Searching in a sorted array by halving', answer: 'binary search', category: 'Algorithms' },
    { question: 'The worst case of quick sort complexity', answer: 'n squared', category: 'Algorithms' },
    { question: 'Storing previously computed results for reuse', answer: 'memoization', category: 'Algorithms' },
    { question: 'Algorithm to detect cycles in a linked list', answer: 'Floyd', category: 'Algorithms' },
    { question: 'Tree traversal: left, root, right', answer: 'inorder', category: 'Algorithms' },
    { question: 'Tree traversal: root, left, right', answer: 'preorder', category: 'Algorithms' },
    { question: 'Tree traversal: left, right, root', answer: 'postorder', category: 'Algorithms' },
    { question: 'Sorting algorithm that counts occurrences', answer: 'counting sort', category: 'Algorithms' },
    { question: 'Technique of solving problem top-down with cache', answer: 'memoization', category: 'Algorithms' },
    { question: 'Notation used to describe algorithm efficiency', answer: 'Big O', category: 'Algorithms' },
    { question: 'Shortest path algorithm for all pairs', answer: 'Floyd Warshall', category: 'Algorithms' },
    { question: 'Algorithm to find shortest path with negative edges', answer: 'Bellman Ford', category: 'Algorithms' },
    { question: 'Search algorithm using a heuristic function', answer: 'A star', category: 'Algorithms' },
    { question: 'Pattern matching algorithm in strings', answer: 'KMP', category: 'Algorithms' },
    { question: 'Algorithm paradigm: try all possibilities', answer: 'backtracking', category: 'Algorithms' },

    // ═══ WEB DEVELOPMENT (50) ═══
    { question: 'What does HTML stand for?', answer: 'HyperText Markup Language', category: 'Web' },
    { question: 'HTTP method to update a resource', answer: 'PUT', category: 'Web' },
    { question: 'Standard port for HTTPS', answer: '443', category: 'Web' },
    { question: 'What does CSS stand for?', answer: 'Cascading Style Sheets', category: 'Web' },
    { question: 'Method that converts JSON string to object', answer: 'JSON parse', category: 'Web' },
    { question: 'What does DOM stand for?', answer: 'Document Object Model', category: 'Web' },
    { question: 'HTML tag for internal CSS', answer: 'style', category: 'Web' },
    { question: 'Property that changes text color in CSS', answer: 'color', category: 'Web' },
    { question: 'HTTP method to retrieve data', answer: 'GET', category: 'Web' },
    { question: 'HTTP method to send data', answer: 'POST', category: 'Web' },
    { question: 'HTTP method to delete a resource', answer: 'DELETE', category: 'Web' },
    { question: 'Status code for success', answer: '200', category: 'Web' },
    { question: 'Status code for not found', answer: '404', category: 'Web' },
    { question: 'Status code for server error', answer: '500', category: 'Web' },
    { question: 'Status code for unauthorized', answer: '401', category: 'Web' },
    { question: 'What does API stand for?', answer: 'Application Programming Interface', category: 'Web' },
    { question: 'What does URL stand for?', answer: 'Uniform Resource Locator', category: 'Web' },
    { question: 'Protocol for real-time bidirectional communication', answer: 'WebSocket', category: 'Web' },
    { question: 'CSS property to make elements flexible', answer: 'flexbox', category: 'Web' },
    { question: 'CSS layout system with rows and columns', answer: 'grid', category: 'Web' },
    { question: 'JavaScript runtime built on Chrome V8 engine', answer: 'Node.js', category: 'Web' },
    { question: 'Package manager for Node.js', answer: 'npm', category: 'Web' },
    { question: 'CSS property for rounded corners', answer: 'border radius', category: 'Web' },
    { question: 'HTML tag for making text bold', answer: 'strong', category: 'Web' },
    { question: 'HTML tag for creating a hyperlink', answer: 'anchor', category: 'Web' },
    { question: 'HTML tag for an unordered list', answer: 'ul', category: 'Web' },
    { question: 'CSS property for transparency', answer: 'opacity', category: 'Web' },
    { question: 'CSS property to hide an element', answer: 'display none', category: 'Web' },
    { question: 'Data format commonly used in web APIs', answer: 'JSON', category: 'Web' },
    { question: 'Web storage that persists after browser close', answer: 'localStorage', category: 'Web' },
    { question: 'Web storage that clears when tab closes', answer: 'sessionStorage', category: 'Web' },
    { question: 'HTTP header for content type', answer: 'Content Type', category: 'Web' },
    { question: 'CSS unit relative to viewport width', answer: 'vw', category: 'Web' },
    { question: 'CSS property to center text', answer: 'text align center', category: 'Web' },
    { question: 'Making a website work on all screen sizes', answer: 'responsive design', category: 'Web' },
    { question: 'HTML tag for input from user', answer: 'form', category: 'Web' },
    { question: 'CSS pseudo-class for mouse over', answer: 'hover', category: 'Web' },
    { question: 'HTML attribute for unique identifier', answer: 'id', category: 'Web' },
    { question: 'HTML attribute for CSS class', answer: 'class', category: 'Web' },
    { question: 'Tool to inspect webpage elements', answer: 'DevTools', category: 'Web' },
    { question: 'CSS property for background image', answer: 'background image', category: 'Web' },
    { question: 'Protocol that loads web pages', answer: 'HTTP', category: 'Web' },
    { question: 'File that tells search engines what to crawl', answer: 'robots.txt', category: 'Web' },
    { question: 'HTML5 element for navigation links', answer: 'nav', category: 'Web' },
    { question: 'CSS property for adding shadow to elements', answer: 'box shadow', category: 'Web' },

    // ═══ JAVASCRIPT (55) ═══
    { question: 'Keyword to declare a block-scoped variable', answer: 'let', category: 'JavaScript' },
    { question: 'Result of typeof null in JavaScript', answer: 'object', category: 'JavaScript' },
    { question: 'Method to add element to end of array', answer: 'push', category: 'JavaScript' },
    { question: 'A function passed as an argument', answer: 'callback', category: 'JavaScript' },
    { question: 'Operator that checks both value and type', answer: 'triple equals', category: 'JavaScript' },
    { question: 'Keyword for constant variable', answer: 'const', category: 'JavaScript' },
    { question: 'Method to remove last element of array', answer: 'pop', category: 'JavaScript' },
    { question: 'Function without a name', answer: 'anonymous function', category: 'JavaScript' },
    { question: 'Arrow syntax for short functions', answer: 'arrow function', category: 'JavaScript' },
    { question: 'Keyword for creating a class', answer: 'class', category: 'JavaScript' },
    { question: 'Method to loop through array elements', answer: 'forEach', category: 'JavaScript' },
    { question: 'Method to create new array from existing', answer: 'map', category: 'JavaScript' },
    { question: 'Method to filter array elements', answer: 'filter', category: 'JavaScript' },
    { question: 'Method to find single element in array', answer: 'find', category: 'JavaScript' },
    { question: 'Method to reduce array to single value', answer: 'reduce', category: 'JavaScript' },
    { question: 'Object for handling asynchronous operations', answer: 'Promise', category: 'JavaScript' },
    { question: 'Keyword to wait for a Promise', answer: 'await', category: 'JavaScript' },
    { question: 'Keyword for async function', answer: 'async', category: 'JavaScript' },
    { question: 'Method to convert object to JSON string', answer: 'JSON stringify', category: 'JavaScript' },
    { question: 'Global object in browser JavaScript', answer: 'window', category: 'JavaScript' },
    { question: 'Method to select element by ID', answer: 'getElementById', category: 'JavaScript' },
    { question: 'Method to add event listener', answer: 'addEventListener', category: 'JavaScript' },
    { question: 'Method to log to console', answer: 'console log', category: 'JavaScript' },
    { question: 'Method to set a timer', answer: 'setTimeout', category: 'JavaScript' },
    { question: 'Method to repeat at intervals', answer: 'setInterval', category: 'JavaScript' },
    { question: 'Keyword for error handling', answer: 'try catch', category: 'JavaScript' },
    { question: 'Keyword to throw an error', answer: 'throw', category: 'JavaScript' },
    { question: 'String method to split into array', answer: 'split', category: 'JavaScript' },
    { question: 'Array method to join into string', answer: 'join', category: 'JavaScript' },
    { question: 'Method to check if variable is array', answer: 'Array isArray', category: 'JavaScript' },
    { question: 'Destructuring syntax uses which brackets?', answer: 'curly braces', category: 'JavaScript' },
    { question: 'Spread operator symbol', answer: 'three dots', category: 'JavaScript' },
    { question: 'Template literals use which character?', answer: 'backtick', category: 'JavaScript' },
    { question: 'Method to get array length', answer: 'length', category: 'JavaScript' },
    { question: 'Keyword referring to current object', answer: 'this', category: 'JavaScript' },
    { question: 'Method to add element to start of array', answer: 'unshift', category: 'JavaScript' },
    { question: 'Method to remove first element of array', answer: 'shift', category: 'JavaScript' },
    { question: 'Method to sort array elements', answer: 'sort', category: 'JavaScript' },
    { question: 'Method to reverse array', answer: 'reverse', category: 'JavaScript' },
    { question: 'Method to extract part of array', answer: 'slice', category: 'JavaScript' },
    { question: 'Falsy value that is a number', answer: 'zero', category: 'JavaScript' },
    { question: 'Special value for not a number', answer: 'NaN', category: 'JavaScript' },
    { question: 'Keyword to import a module', answer: 'import', category: 'JavaScript' },
    { question: 'Keyword to export from module', answer: 'export', category: 'JavaScript' },
    { question: 'Method to fetch data from server', answer: 'fetch', category: 'JavaScript' },
    { question: 'Short circuit evaluation operator', answer: 'logical OR', category: 'JavaScript' },
    { question: 'Nullish coalescing operator symbol', answer: 'double question mark', category: 'JavaScript' },
    { question: 'Optional chaining operator', answer: 'question dot', category: 'JavaScript' },
    { question: 'Method to convert string to number', answer: 'parseInt', category: 'JavaScript' },
    { question: 'Event when page finishes loading', answer: 'DOMContentLoaded', category: 'JavaScript' },

    // ═══ PYTHON (45) ═══
    { question: 'Python function to print output', answer: 'print', category: 'Python' },
    { question: 'Python keyword to define a function', answer: 'def', category: 'Python' },
    { question: 'Python data type for ordered mutable collection', answer: 'list', category: 'Python' },
    { question: 'Python data type for immutable ordered collection', answer: 'tuple', category: 'Python' },
    { question: 'Python data type for key-value pairs', answer: 'dictionary', category: 'Python' },
    { question: 'Python keyword for conditional', answer: 'if', category: 'Python' },
    { question: 'Python keyword for looping', answer: 'for', category: 'Python' },
    { question: 'Python keyword to import a module', answer: 'import', category: 'Python' },
    { question: 'Python function to get length', answer: 'len', category: 'Python' },
    { question: 'Python function to get data type', answer: 'type', category: 'Python' },
    { question: 'Python function to get range of numbers', answer: 'range', category: 'Python' },
    { question: 'Python function to get user input', answer: 'input', category: 'Python' },
    { question: 'Python operator for integer division', answer: 'double slash', category: 'Python' },
    { question: 'Python operator for exponentiation', answer: 'double star', category: 'Python' },
    { question: 'Python package installer', answer: 'pip', category: 'Python' },
    { question: 'Python web framework by Django', answer: 'Django', category: 'Python' },
    { question: 'Lightweight Python web framework', answer: 'Flask', category: 'Python' },
    { question: 'Python library for data analysis', answer: 'Pandas', category: 'Python' },
    { question: 'Python library for numerical computing', answer: 'NumPy', category: 'Python' },
    { question: 'Python library for machine learning', answer: 'scikit learn', category: 'Python' },
    { question: 'Python library for data visualization', answer: 'matplotlib', category: 'Python' },
    { question: 'Python keyword for none value', answer: 'None', category: 'Python' },
    { question: 'Python keyword for boolean true', answer: 'True', category: 'Python' },
    { question: 'Python method to add item to list', answer: 'append', category: 'Python' },
    { question: 'Python method to remove item from list', answer: 'remove', category: 'Python' },
    { question: 'Feature that creates list in one line', answer: 'list comprehension', category: 'Python' },
    { question: 'Python virtual environment tool', answer: 'venv', category: 'Python' },
    { question: 'Python keyword for class inheritance', answer: 'class', category: 'Python' },
    { question: 'Python special method for constructor', answer: 'init', category: 'Python' },
    { question: 'First parameter of Python class methods', answer: 'self', category: 'Python' },
    { question: 'Python function to open a file', answer: 'open', category: 'Python' },
    { question: 'Python keyword for exception handling', answer: 'try except', category: 'Python' },
    { question: 'Python deep learning library by Google', answer: 'TensorFlow', category: 'Python' },
    { question: 'Python deep learning library by Facebook', answer: 'PyTorch', category: 'Python' },
    { question: 'Python string method to remove whitespace', answer: 'strip', category: 'Python' },

    // ═══ JAVA & OOP (40) ═══
    { question: 'Parent class of all Java classes', answer: 'Object', category: 'Java' },
    { question: 'Keyword for inheritance in Java', answer: 'extends', category: 'Java' },
    { question: 'Default value of boolean in Java', answer: 'false', category: 'Java' },
    { question: 'Interface for ordered collections in Java', answer: 'List', category: 'Java' },
    { question: 'Subclass provides its own method implementation', answer: 'overriding', category: 'OOP' },
    { question: 'Hiding internal details showing functionality', answer: 'abstraction', category: 'OOP' },
    { question: 'Wrapping data and methods together', answer: 'encapsulation', category: 'OOP' },
    { question: 'One class getting properties of another', answer: 'inheritance', category: 'OOP' },
    { question: 'Same method name with different parameters', answer: 'overloading', category: 'OOP' },
    { question: 'Many forms of same method', answer: 'polymorphism', category: 'OOP' },
    { question: 'Blueprint for creating objects', answer: 'class', category: 'OOP' },
    { question: 'Instance of a class', answer: 'object', category: 'OOP' },
    { question: 'Special method called when object is created', answer: 'constructor', category: 'OOP' },
    { question: 'Java keyword for implementing interface', answer: 'implements', category: 'Java' },
    { question: 'Java keyword for abstract class', answer: 'abstract', category: 'Java' },
    { question: 'Access modifier visible everywhere', answer: 'public', category: 'Java' },
    { question: 'Access modifier visible only in class', answer: 'private', category: 'Java' },
    { question: 'Access modifier visible in package', answer: 'protected', category: 'Java' },
    { question: 'Java keyword to prevent inheritance', answer: 'final', category: 'Java' },
    { question: 'Java keyword for static methods', answer: 'static', category: 'Java' },
    { question: 'Java collection that does not allow duplicates', answer: 'Set', category: 'Java' },
    { question: 'Java collection for key-value pairs', answer: 'HashMap', category: 'Java' },
    { question: 'Java build tool by Apache', answer: 'Maven', category: 'Java' },
    { question: 'Java build tool with Groovy scripts', answer: 'Gradle', category: 'Java' },
    { question: 'Java framework for enterprise applications', answer: 'Spring', category: 'Java' },
    { question: 'Design pattern that ensures only one instance', answer: 'singleton', category: 'OOP' },
    { question: 'Design pattern that creates objects', answer: 'factory', category: 'OOP' },
    { question: 'Design pattern that notifies observers', answer: 'observer', category: 'OOP' },
    { question: 'Principle: class should have one responsibility', answer: 'SRP', category: 'OOP' },
    { question: 'SOLID principle for interface segregation', answer: 'ISP', category: 'OOP' },

    // ═══ DATABASE (45) ═══
    { question: 'What does SQL stand for?', answer: 'Structured Query Language', category: 'Database' },
    { question: 'Command to remove all records from table', answer: 'TRUNCATE', category: 'Database' },
    { question: 'What does DDL stand for?', answer: 'Data Definition Language', category: 'Database' },
    { question: 'Constraint ensuring all values are unique', answer: 'UNIQUE', category: 'Database' },
    { question: 'Virtual table based on SQL query result', answer: 'view', category: 'Database' },
    { question: 'SQL command to retrieve data', answer: 'SELECT', category: 'Database' },
    { question: 'SQL command to insert data', answer: 'INSERT', category: 'Database' },
    { question: 'SQL command to modify data', answer: 'UPDATE', category: 'Database' },
    { question: 'SQL command to remove data', answer: 'DELETE', category: 'Database' },
    { question: 'SQL command to create a table', answer: 'CREATE TABLE', category: 'Database' },
    { question: 'Combining rows from two tables', answer: 'JOIN', category: 'Database' },
    { question: 'Key that uniquely identifies a record', answer: 'primary key', category: 'Database' },
    { question: 'Key that references another table', answer: 'foreign key', category: 'Database' },
    { question: 'Process of organizing tables to reduce redundancy', answer: 'normalization', category: 'Database' },
    { question: 'SQL clause to filter results', answer: 'WHERE', category: 'Database' },
    { question: 'SQL clause to sort results', answer: 'ORDER BY', category: 'Database' },
    { question: 'SQL clause to group results', answer: 'GROUP BY', category: 'Database' },
    { question: 'SQL function to count rows', answer: 'COUNT', category: 'Database' },
    { question: 'SQL function to calculate average', answer: 'AVG', category: 'Database' },
    { question: 'SQL function to find maximum', answer: 'MAX', category: 'Database' },
    { question: 'NoSQL document-oriented database', answer: 'MongoDB', category: 'Database' },
    { question: 'Popular open-source relational database', answer: 'MySQL', category: 'Database' },
    { question: 'Advanced open-source relational database', answer: 'PostgreSQL', category: 'Database' },
    { question: 'In-memory key-value data store', answer: 'Redis', category: 'Database' },
    { question: 'Database property: Atomicity Consistency Isolation Durability', answer: 'ACID', category: 'Database' },
    { question: 'SQL wildcard character for any characters', answer: 'percent', category: 'Database' },
    { question: 'Speeds up database queries', answer: 'index', category: 'Database' },
    { question: 'Stored procedure executed automatically on event', answer: 'trigger', category: 'Database' },
    { question: 'Query within another query', answer: 'subquery', category: 'Database' },
    { question: 'Lightweight file-based database', answer: 'SQLite', category: 'Database' },

    // ═══ CLOUD & DEVOPS (40) ═══
    { question: 'Primary computing service in AWS', answer: 'EC2', category: 'Cloud' },
    { question: 'Tool for container orchestration', answer: 'Kubernetes', category: 'DevOps' },
    { question: 'What is used for version control?', answer: 'Git', category: 'DevOps' },
    { question: 'Platform as a Service abbreviation', answer: 'PaaS', category: 'Cloud' },
    { question: 'Infrastructure as Code tool by HashiCorp', answer: 'Terraform', category: 'DevOps' },
    { question: 'Containerization platform', answer: 'Docker', category: 'DevOps' },
    { question: 'File that defines Docker image', answer: 'Dockerfile', category: 'DevOps' },
    { question: 'CI/CD platform by Microsoft', answer: 'Azure DevOps', category: 'DevOps' },
    { question: 'CI/CD tool that uses Jenkinsfile', answer: 'Jenkins', category: 'DevOps' },
    { question: 'AWS storage service for files', answer: 'S3', category: 'Cloud' },
    { question: 'AWS serverless compute service', answer: 'Lambda', category: 'Cloud' },
    { question: 'AWS managed database service', answer: 'RDS', category: 'Cloud' },
    { question: 'Microsoft cloud platform', answer: 'Azure', category: 'Cloud' },
    { question: 'Google cloud platform abbreviation', answer: 'GCP', category: 'Cloud' },
    { question: 'Configuration management tool', answer: 'Ansible', category: 'DevOps' },
    { question: 'File defining Docker multi-container apps', answer: 'docker compose', category: 'DevOps' },
    { question: 'Monitoring and alerting tool', answer: 'Prometheus', category: 'DevOps' },
    { question: 'Visualization tool for metrics', answer: 'Grafana', category: 'DevOps' },
    { question: 'Practice of continuous integration', answer: 'CI', category: 'DevOps' },
    { question: 'Practice of continuous deployment', answer: 'CD', category: 'DevOps' },
    { question: 'Service mesh for microservices', answer: 'Istio', category: 'DevOps' },
    { question: 'AWS content delivery network', answer: 'CloudFront', category: 'Cloud' },
    { question: 'AWS DNS service', answer: 'Route 53', category: 'Cloud' },
    { question: 'Container image storage', answer: 'registry', category: 'DevOps' },
    { question: 'Infrastructure as a Service abbreviation', answer: 'IaaS', category: 'Cloud' },
    { question: 'Software as a Service abbreviation', answer: 'SaaS', category: 'Cloud' },
    { question: 'AWS messaging queue service', answer: 'SQS', category: 'Cloud' },
    { question: 'Load balancing distributes traffic to', answer: 'servers', category: 'Cloud' },
    { question: 'Git hosting platform by Microsoft', answer: 'GitHub', category: 'DevOps' },
    { question: 'Git hosting platform with CI built in', answer: 'GitLab', category: 'DevOps' },

    // ═══ SECURITY (35) ═══
    { question: 'Protocol that secures network communication', answer: 'HTTPS', category: 'Security' },
    { question: 'Acquiring data by pretending to be trustworthy', answer: 'phishing', category: 'Security' },
    { question: 'Malicious software designed to damage computer', answer: 'malware', category: 'Security' },
    { question: 'Software that locks files and demands payment', answer: 'ransomware', category: 'Security' },
    { question: 'Attack that floods server with traffic', answer: 'DDoS', category: 'Security' },
    { question: 'Injecting malicious SQL into queries', answer: 'SQL injection', category: 'Security' },
    { question: 'Injecting scripts into web pages', answer: 'XSS', category: 'Security' },
    { question: 'Converting plain text to unreadable format', answer: 'encryption', category: 'Security' },
    { question: 'Converting encrypted text back', answer: 'decryption', category: 'Security' },
    { question: 'One-way function to generate fixed-size output', answer: 'hashing', category: 'Security' },
    { question: 'Network security system that filters traffic', answer: 'firewall', category: 'Security' },
    { question: 'Virtual Private Network abbreviation', answer: 'VPN', category: 'Security' },
    { question: 'Two-factor authentication abbreviation', answer: '2FA', category: 'Security' },
    { question: 'Secure shell protocol', answer: 'SSH', category: 'Security' },
    { question: 'Digital certificate authority', answer: 'CA', category: 'Security' },
    { question: 'Public key cryptography uses how many keys?', answer: 'two', category: 'Security' },
    { question: 'Authentication token standard for web', answer: 'JWT', category: 'Security' },
    { question: 'Open standard for authorization', answer: 'OAuth', category: 'Security' },
    { question: 'Cross-site request forgery abbreviation', answer: 'CSRF', category: 'Security' },
    { question: 'Security testing by simulating attacks', answer: 'penetration testing', category: 'Security' },
    { question: 'Malware that logs keyboard inputs', answer: 'keylogger', category: 'Security' },
    { question: 'Malware disguised as legitimate software', answer: 'trojan', category: 'Security' },
    { question: 'Program that replicates itself', answer: 'virus', category: 'Security' },
    { question: 'Self-replicating malware spreading via networks', answer: 'worm', category: 'Security' },
    { question: 'Security principle of least privilege means', answer: 'minimum access', category: 'Security' },

    // ═══ AI & ML (40) ═══
    { question: 'Learning rate in neural networks is a', answer: 'hyperparameter', category: 'AI' },
    { question: 'Model trained on labeled data', answer: 'supervised learning', category: 'AI' },
    { question: 'Python library for data manipulation', answer: 'Pandas', category: 'AI' },
    { question: 'Model trained on unlabeled data', answer: 'unsupervised learning', category: 'AI' },
    { question: 'AI that learns through rewards and penalties', answer: 'reinforcement learning', category: 'AI' },
    { question: 'Network of interconnected nodes inspired by brain', answer: 'neural network', category: 'AI' },
    { question: 'Deep learning framework by Google', answer: 'TensorFlow', category: 'AI' },
    { question: 'Deep learning framework by Meta', answer: 'PyTorch', category: 'AI' },
    { question: 'AI model that generates text', answer: 'GPT', category: 'AI' },
    { question: 'AI model that generates images from text', answer: 'diffusion model', category: 'AI' },
    { question: 'Reducing model overfitting technique', answer: 'regularization', category: 'AI' },
    { question: 'Splitting data for training and evaluation', answer: 'train test split', category: 'AI' },
    { question: 'Metric for classification accuracy', answer: 'accuracy', category: 'AI' },
    { question: 'When model performs well on training but not test data', answer: 'overfitting', category: 'AI' },
    { question: 'When model is too simple to learn patterns', answer: 'underfitting', category: 'AI' },
    { question: 'Algorithm for classifying by finding nearest neighbors', answer: 'KNN', category: 'AI' },
    { question: 'Algorithm using decision boundaries', answer: 'SVM', category: 'AI' },
    { question: 'Tree-based classification algorithm', answer: 'decision tree', category: 'AI' },
    { question: 'Ensemble of decision trees', answer: 'random forest', category: 'AI' },
    { question: 'Gradient boosting implementation', answer: 'XGBoost', category: 'AI' },
    { question: 'Algorithm for grouping similar data', answer: 'K-means', category: 'AI' },
    { question: 'Reducing number of features', answer: 'PCA', category: 'AI' },
    { question: 'Natural language processing abbreviation', answer: 'NLP', category: 'AI' },
    { question: 'Computer vision task of identifying objects', answer: 'object detection', category: 'AI' },
    { question: 'Neural network for image processing', answer: 'CNN', category: 'AI' },
    { question: 'Neural network for sequential data', answer: 'RNN', category: 'AI' },
    { question: 'Attention-based neural network architecture', answer: 'transformer', category: 'AI' },
    { question: 'AI chatbot by OpenAI', answer: 'ChatGPT', category: 'AI' },
    { question: 'Process of feeding data into a model', answer: 'training', category: 'AI' },
    { question: 'Using trained model on new data', answer: 'inference', category: 'AI' },

    // ═══ NETWORKING (35) ═══
    { question: 'Unique address assigned to every device on network', answer: 'IP address', category: 'Networking' },
    { question: 'Protocol for sending emails', answer: 'SMTP', category: 'Networking' },
    { question: 'Protocol for transferring files', answer: 'FTP', category: 'Networking' },
    { question: 'Protocol that translates domain names to IP', answer: 'DNS', category: 'Networking' },
    { question: 'Protocol for reliable data transmission', answer: 'TCP', category: 'Networking' },
    { question: 'Fast connectionless protocol', answer: 'UDP', category: 'Networking' },
    { question: 'Device that connects different networks', answer: 'router', category: 'Networking' },
    { question: 'Device that connects devices in same network', answer: 'switch', category: 'Networking' },
    { question: 'Physical address of network interface', answer: 'MAC address', category: 'Networking' },
    { question: 'Network model with 7 layers', answer: 'OSI model', category: 'Networking' },
    { question: 'Top layer of OSI model', answer: 'application layer', category: 'Networking' },
    { question: 'Network covering a small area like office', answer: 'LAN', category: 'Networking' },
    { question: 'Network covering large geographic area', answer: 'WAN', category: 'Networking' },
    { question: 'Wireless networking standard', answer: 'WiFi', category: 'Networking' },
    { question: 'Network topology where all connect to center', answer: 'star', category: 'Networking' },
    { question: 'Maximum data transfer rate', answer: 'bandwidth', category: 'Networking' },
    { question: 'Time delay in network communication', answer: 'latency', category: 'Networking' },
    { question: 'Breaking data into smaller units for transmission', answer: 'packet', category: 'Networking' },
    { question: 'Port number for HTTP', answer: '80', category: 'Networking' },
    { question: 'Port number for SSH', answer: '22', category: 'Networking' },
    { question: 'Protocol for secure file transfer', answer: 'SFTP', category: 'Networking' },
    { question: 'Network address translation abbreviation', answer: 'NAT', category: 'Networking' },
    { question: 'Protocol for assigning IP addresses automatically', answer: 'DHCP', category: 'Networking' },
    { question: 'Dividing network into smaller segments', answer: 'subnetting', category: 'Networking' },
    { question: 'Network device that amplifies signal', answer: 'repeater', category: 'Networking' },

    // ═══ OPERATING SYSTEMS (30) ═══
    { question: 'Core of an operating system', answer: 'kernel', category: 'OS' },
    { question: 'Running multiple programs at same time', answer: 'multitasking', category: 'OS' },
    { question: 'Unit of execution in an operating system', answer: 'process', category: 'OS' },
    { question: 'Lightweight process within a process', answer: 'thread', category: 'OS' },
    { question: 'When two processes wait for each other forever', answer: 'deadlock', category: 'OS' },
    { question: 'Memory management technique using pages', answer: 'paging', category: 'OS' },
    { question: 'Using disk as extension of RAM', answer: 'virtual memory', category: 'OS' },
    { question: 'Open source operating system kernel', answer: 'Linux', category: 'OS' },
    { question: 'Linux command to list files', answer: 'ls', category: 'OS' },
    { question: 'Linux command to change directory', answer: 'cd', category: 'OS' },
    { question: 'Linux command to copy files', answer: 'cp', category: 'OS' },
    { question: 'Linux command to move files', answer: 'mv', category: 'OS' },
    { question: 'Linux command to delete files', answer: 'rm', category: 'OS' },
    { question: 'Linux command to create directory', answer: 'mkdir', category: 'OS' },
    { question: 'Linux command to show current directory', answer: 'pwd', category: 'OS' },
    { question: 'Linux command to view file contents', answer: 'cat', category: 'OS' },
    { question: 'Linux text editor in terminal', answer: 'vim', category: 'OS' },
    { question: 'Linux command to search text in files', answer: 'grep', category: 'OS' },
    { question: 'Linux command to change file permissions', answer: 'chmod', category: 'OS' },
    { question: 'File system hierarchy root in Linux', answer: 'slash', category: 'OS' },
    { question: 'Linux user with full system access', answer: 'root', category: 'OS' },
    { question: 'CPU scheduling algorithm: first come first served', answer: 'FCFS', category: 'OS' },
    { question: 'CPU scheduling with time slices', answer: 'round robin', category: 'OS' },
    { question: 'OS concept where process waits for resource', answer: 'blocking', category: 'OS' },
    { question: 'Linux command to install packages on Ubuntu', answer: 'apt', category: 'OS' },

    // ═══ GIT (25) ═══
    { question: 'Git command to initialize a repository', answer: 'git init', category: 'Git' },
    { question: 'Git command to stage changes', answer: 'git add', category: 'Git' },
    { question: 'Git command to save changes', answer: 'git commit', category: 'Git' },
    { question: 'Git command to upload to remote', answer: 'git push', category: 'Git' },
    { question: 'Git command to download from remote', answer: 'git pull', category: 'Git' },
    { question: 'Git command to create a branch', answer: 'git branch', category: 'Git' },
    { question: 'Git command to switch branches', answer: 'git checkout', category: 'Git' },
    { question: 'Git command to combine branches', answer: 'git merge', category: 'Git' },
    { question: 'Git command to copy a repository', answer: 'git clone', category: 'Git' },
    { question: 'Git command to check status', answer: 'git status', category: 'Git' },
    { question: 'Git command to view commit history', answer: 'git log', category: 'Git' },
    { question: 'Git command to see differences', answer: 'git diff', category: 'Git' },
    { question: 'Git command to discard changes', answer: 'git reset', category: 'Git' },
    { question: 'Git command to temporarily save changes', answer: 'git stash', category: 'Git' },
    { question: 'File that tells Git what to ignore', answer: 'gitignore', category: 'Git' },
    { question: 'Git strategy to replay commits on top', answer: 'rebase', category: 'Git' },
    { question: 'Git conflict happens when', answer: 'same line changed', category: 'Git' },
    { question: 'Default branch name in Git', answer: 'main', category: 'Git' },
    { question: 'Git remote named by default', answer: 'origin', category: 'Git' },
    { question: 'Request to merge code on GitHub', answer: 'pull request', category: 'Git' },

    // ═══ REACT (30) ═══
    { question: 'React function that returns UI elements', answer: 'component', category: 'React' },
    { question: 'React hook for managing state', answer: 'useState', category: 'React' },
    { question: 'React hook for side effects', answer: 'useEffect', category: 'React' },
    { question: 'Passing data from parent to child component', answer: 'props', category: 'React' },
    { question: 'React syntax extension that looks like HTML', answer: 'JSX', category: 'React' },
    { question: 'React tool for client-side routing', answer: 'React Router', category: 'React' },
    { question: 'State management library for React', answer: 'Redux', category: 'React' },
    { question: 'React hook for accessing DOM elements', answer: 'useRef', category: 'React' },
    { question: 'React hook for sharing data without props', answer: 'useContext', category: 'React' },
    { question: 'React framework for server-side rendering', answer: 'Next.js', category: 'React' },
    { question: 'Process of updating only changed parts of DOM', answer: 'reconciliation', category: 'React' },
    { question: 'In-memory representation of real DOM', answer: 'virtual DOM', category: 'React' },
    { question: 'React method to render component to DOM', answer: 'render', category: 'React' },
    { question: 'React attribute for unique list items', answer: 'key', category: 'React' },
    { question: 'React tool for creating project quickly', answer: 'create react app', category: 'React' },
    { question: 'Modern React build tool', answer: 'Vite', category: 'React' },
    { question: 'React hook for complex state logic', answer: 'useReducer', category: 'React' },
    { question: 'React hook for memoizing values', answer: 'useMemo', category: 'React' },
    { question: 'React hook for memoizing functions', answer: 'useCallback', category: 'React' },
    { question: 'Rendering React on server', answer: 'SSR', category: 'React' },

    // ═══ SOFTWARE ENGINEERING (30) ═══
    { question: 'Finding errors in software code', answer: 'debugging', category: 'Software Engineering' },
    { question: 'Development methodology with sprints', answer: 'Agile', category: 'Software Engineering' },
    { question: 'Agile framework with daily standups', answer: 'Scrum', category: 'Software Engineering' },
    { question: 'Visual board for tracking tasks', answer: 'Kanban', category: 'Software Engineering' },
    { question: 'Testing individual units of code', answer: 'unit testing', category: 'Software Engineering' },
    { question: 'Testing how components work together', answer: 'integration testing', category: 'Software Engineering' },
    { question: 'Testing the complete application', answer: 'end to end testing', category: 'Software Engineering' },
    { question: 'Writing tests before code', answer: 'TDD', category: 'Software Engineering' },
    { question: 'Improving code without changing functionality', answer: 'refactoring', category: 'Software Engineering' },
    { question: 'Tracking bugs and features', answer: 'issue tracker', category: 'Software Engineering' },
    { question: 'Document describing software requirements', answer: 'SRS', category: 'Software Engineering' },
    { question: 'Diagram showing class relationships', answer: 'UML', category: 'Software Engineering' },
    { question: 'Architecture with small independent services', answer: 'microservices', category: 'Software Engineering' },
    { question: 'Architecture with single large application', answer: 'monolith', category: 'Software Engineering' },
    { question: 'API architectural style using HTTP methods', answer: 'REST', category: 'Software Engineering' },
    { question: 'API query language by Facebook', answer: 'GraphQL', category: 'Software Engineering' },
    { question: 'Message broker for event-driven systems', answer: 'Kafka', category: 'Software Engineering' },
    { question: 'Software development lifecycle abbreviation', answer: 'SDLC', category: 'Software Engineering' },
    { question: 'Code review before merging', answer: 'pull request review', category: 'Software Engineering' },
    { question: 'Automated code quality check', answer: 'linting', category: 'Software Engineering' },

    // ═══ HARDWARE & MISC (30) ═══
    { question: 'Brain of the computer', answer: 'CPU', category: 'Hardware' },
    { question: 'Temporary fast memory', answer: 'RAM', category: 'Hardware' },
    { question: 'Long-term storage device', answer: 'hard drive', category: 'Hardware' },
    { question: 'Faster storage using flash memory', answer: 'SSD', category: 'Hardware' },
    { question: 'Graphics processing unit', answer: 'GPU', category: 'Hardware' },
    { question: 'Circuit board that connects all components', answer: 'motherboard', category: 'Hardware' },
    { question: 'Power supply unit abbreviation', answer: 'PSU', category: 'Hardware' },
    { question: 'Input device for typing', answer: 'keyboard', category: 'Hardware' },
    { question: 'Pointing input device', answer: 'mouse', category: 'Hardware' },
    { question: 'Visual output device', answer: 'monitor', category: 'Hardware' },
    { question: 'Smallest unit of data', answer: 'bit', category: 'Hardware' },
    { question: 'Eight bits make one', answer: 'byte', category: 'Hardware' },
    { question: '1024 bytes equals one', answer: 'kilobyte', category: 'Hardware' },
    { question: 'Binary number system base', answer: 'two', category: 'Hardware' },
    { question: 'Hexadecimal number system base', answer: 'sixteen', category: 'Hardware' },
    { question: 'Small fast memory close to CPU', answer: 'cache', category: 'Hardware' },
    { question: 'Basic input output system', answer: 'BIOS', category: 'Hardware' },
    { question: 'Internet of Things abbreviation', answer: 'IoT', category: 'Hardware' },
    { question: 'Single board computer popular for projects', answer: 'Raspberry Pi', category: 'Hardware' },
    { question: 'Microcontroller board for prototyping', answer: 'Arduino', category: 'Hardware' },
    { question: 'Type of software that is free to use and modify', answer: 'open source', category: 'Software Engineering' },
    { question: 'Version of software released for testing', answer: 'beta', category: 'Software Engineering' },
    { question: 'Minimum viable product abbreviation', answer: 'MVP', category: 'Software Engineering' },
    { question: 'User interface abbreviation', answer: 'UI', category: 'Software Engineering' },
    { question: 'User experience abbreviation', answer: 'UX', category: 'Software Engineering' },
    { question: 'Application programming interface abbreviation', answer: 'API', category: 'Software Engineering' },
    { question: 'Integrated development environment abbreviation', answer: 'IDE', category: 'Software Engineering' },
    { question: 'Popular code editor by Microsoft', answer: 'VS Code', category: 'Software Engineering' },
    { question: 'Code hosting and collaboration platform', answer: 'GitHub', category: 'Software Engineering' },
    { question: 'Package manager for JavaScript', answer: 'npm', category: 'Software Engineering' },
];

module.exports = technicalQuestions;
